language: python
sudo: enabled
python:
  - 3.5
  - 3.6
install:
  - pip install python-coveralls
  - pip install colorama
script:
  - make test
  - coverage run test_rpn.py

after_success:
  - coveralls
